### ISSUE TITLE
Does this client work on Cloud Foundry

### ISSUE THREAD

**Issue by febinrejoe** [amenezes/config-client#15]
Does this client work for the Spring Cloud Config Server on Cloud Foundry? The Config Server on Cloud Foundry uses OAuth 2.0 and the credentials for the Config Server are injected to the bound App as VCAP environment variables.

**Comment by amenezes** [comment]
@febinrejoe,

the current version doesn't' work with authentication yet. But that's an interesting feature, I will try to put this on next release.

**Comment by febinrejoe** [comment]
Thanks @amenezes

**Comment by dashaun** [comment]
@amenezes I'm inviting you to my personal Cloud Foundry installation so that you can do development and testing!  I'll email you more info.

**Comment by amenezes** [comment]
@febinrejoe and @dashaun,

I have shared a pre-release version to test the integration with Cloud Foundry. If you can test and send me some feedback.

Link of version: [0.4.0a0](https://pypi.org/project/config-client/0.4.0a0/) *pre-release*
Simple example application: https://github.com/amenezes/simpleweb
Example configuration: https://github.com/amenezes/spring_config

Dashaun I'd like to take some screenshots of setup process to generate a better documentation in next release.

**Comment by febinrejoe** [comment]
Thanks @amenezes . I will test this sometime this week and provide feedback.

**Comment by jgodara** [comment]
@amenezes is basic authentication supported in the pre-release version? If this is something on this project's roadmap, I can send in a PR!

**Comment by amenezes** [comment]
@realbucksavage,

I believe that basic authentication mechanism currently only work on the workflow to integrate with Cloud Foundry, on branch [ft-15](https://github.com/amenezes/config-client/blob/ft-15/config/auth.py#L49).

But certainly we can work to refactor and add support to more use cases and keep current work. I really appreciate your help. :smiley:

If you need some help don't hesitate to contacte me.

**Comment by realbucksavage** [comment]
@amenezes for now, I'm using a little spin-off of your project to get around my use-case.
I'll try to contribute when I can.

Thanks for this project.

**Comment by amenezes** [comment]
@realbucksavage this is great!

@febinrejoe and @dashaun I released final version [:package: 0.4.0](https://pypi.org/project/config-client/0.4.0/) with Cloud Foundry integration. I will close this issue, but if any adjustment is required or for further information, just contact me or open a new issue.

Thank you all for the help and participation.
