### ISSUE TITLE
Documentation Issue: get_attribute method exists in config_client, not config dictionary

### ISSUE THREAD

**Issue by amitga-rnd** [amenezes/config-client#16]
At: https://github.com/amenezes/config-client#using-standard-client
It is stated that `get_attribute` method can be used:
```
# option 3: using get_attribute method
config_client.config.get_attribute('spring.cloud.consul.port')
```
but `config_client.config` is a dictionary, and doesn't have that method.
It should be fixed to: 
```
# option 3: using get_attribute method
config_client.get_attribute('spring.cloud.consul.port')
```

**Comment by amenezes** [comment]
@amitga-rnd thanks for your observation.

The fixes will be available on next release.
