### ISSUE TITLE
how to use a diff config server in Cloud Foundry?

### ISSUE THREAD

**Issue by anishp55** [amenezes/config-client#20]
we have implemented our own config server, is there away to override the p-config-server?

```
default_vcap_services = json.dumps(
    {
        "p-config-server": [
            {
                "credentials": {
                    "uri": "",
                    "access_token_uri": "",
                    "client_id": "",
                    "client_secret": ""
                }
            }
        ]
    }
)
```

**Comment by amenezes** [comment]
@anishp55 I released version `0.5.0` with your PR merged.

I made some minor modifications to increase test coverage and also to adjust the code style. 

Thanks for your contribution :muscle:
