### ISSUE TITLE
There is not config_client decorator to get singleton instance

### ISSUE THREAD

**Issue by luiscoms** [amenezes/config-client#32]
If I decorate two or more functions, it will call server both times.
It would be great a decorator that return singleton instance.

```python
import logging
from config.spring import config_client

@config_client()
def foo(client):
   logging.debug(client.config)

@config_client()  # call again
def bar(client):
   logging.debug(client.config)

```

Suggestion

```python
import logging
from config.spring import config_client

@config_client(singleton=True)
def foo(client):
   logging.debug(client.config)

@config_client(singleton=True)
def bar(client):
   logging.debug(client.config)

```

Or

```python
import logging
from config.spring import config_client_singleton

@config_client_singleton
def foo(client):
   logging.debug(client.config)

@config_client_singleton
def bar(client):
   logging.debug(client.config)

```

**Comment by amenezes** [comment]
@luiscoms,

This behavior already exists. Try use `@singleton` decorator available in the [`core`](https://github.com/amenezes/config-client/blob/master/config/core.py) module. For example:

```python
from config.spring import config_client
from config.core import singleton


@singleton
@config_client()
def foo(client):
   return client

@config_client()
def bar(client):
   return client

a = foo()
b = foo()
c = bar()
d = bar()

print(id(a))
print(id(b)) # a == b
print(id(c))
print(id(d)) # c != d
```

I'll keep this issue open until the documentation is updated.

**Comment by luiscoms** [comment]
I understood, my suggestion is create a library decorador, not create myself decorator.

**Comment by amenezes** [comment]
Sorry I didn't understand this point: "_create a decorator library, not create myself decorator_"?

The decorator `@singleton` is now available for use and is used in the lib. All you need to do is import the decorator and use it as in a stack.

Could you detail the issue request a little more?

**Comment by luiscoms** [comment]
Sure, my case is the same as I explained above.

```python
import logging
from config.spring import config_client

@config_client()
def foo(client):
   # do stuff with client
   logging.debug(client.config)

@config_client()
def bar(client):
   # do stuff with client
   logging.debug(client.config)
```

**Comment by amenezes** [comment]
@luiscoms,

Sorry, as this issue is approximately for 1 year and a half without any change, I decided to close it with `wontfix` status however if there is any change in the general interest we can reevaluate.
