### ISSUE TITLE
Support for p.config-server

### ISSUE THREAD

**Issue by samarsinghal** [amenezes/config-client#35]
The library is working fine for Spring Cloud Services 1.x and 2.x (p-config-server) but failing for 3.x config server service instances (p.config-server). 

Below files need to be updated to support p.config-server along with p-config-server 

config/cfenv.py 
config/cloudfoundry.py 
tests/unit/test_cfenv.py 
tests/unit/test_oauth2.py

**Comment by amenezes** [comment]
@samarsinghal sorry for delay. Did you try use as in the example below?

```python
from config.cf import CF
from config.cfenv import CFenv

cf = CF(cfenv=CFEnv(vcap_service_prefix="p.config-server"))
cf.get_config()
```
Could you share some log with me?

**Comment by amenezes** [comment]
@samarsinghal I will close this issue for now. If you have any update, some data to share or log, that help me to understand whats happen or some feedback from my last comment I'd be happy to be able to help you.
