### ISSUE TITLE
Oauth2 integration

### ISSUE THREAD

**Issue by rakshitcgupta** [amenezes/config-client#38]
Hi, as there is no detail on using the Oauth in the documentation, it will be helpful if we provide the documention and/or example for using it.

**Comment by amenezes** [comment]
@rakshitcgupta,

Could you try test version [`0.11.1a0`](https://pypi.org/project/config-client/0.11.1a0/) and follow this [instructions](https://config-client.amenezes.net/docs/client/1.-standard-client/#spring-cloud-config-with-oauth2).

It would be very helpful too if you can provide some feedback.

**Comment by amenezes** [comment]
fixed in version [0.11.1](https://github.com/amenezes/config-client/releases/tag/0.11.1)
