### ISSUE TITLE
How to invoke config server using basic authentication

### ISSUE THREAD

**Issue by rmotapar** [amenezes/config-client#40]
Hi,
Our spring config server is protected using basic authentication. Is it possible to use config-client to send a basic auth header with the request? If yes, an example would be very helpful.

Thanks!

**Comment by amenezes** [comment]
@rmotapar,

Yes it's possible. Try use [HTTPBasicAuth](https://2.python-requests.org/en/master/user/authentication/).

For example:

```python
from requests.auth import HTTPBasicAuth

from config.spring import ConfigClient

client = ConfigClient(app_name="simpleweb000")
client.get_config(auth=HTTPBasicAuth('user', password))
```

I will update the project documentation with this question.

Thanks.

**Comment by amenezes** [comment]
@rmotapar the example solved your question?

The project [documentation](http://config-client.amenezes.net/docs/client/1.-standard-client/#authentication) was been updated.

**Comment by rmotapar** [comment]
@amenezes Thank you so much for the quick response. I have verified this using your example and it's working!
