### ISSUE TITLE
Client not actually async

### ISSUE THREAD

**Issue by joshuahaertel** [amenezes/config-client#43]
I suggest removing references about asyncio until the client is actually asyncio compliant.

If it were asyncio compliant, the example code would include the `await` keyword, like so:
```
async def start(config_client):
    await config_client.get_config()
    print(config_client.config)

await start(config_client)
```

The clarification is important, as applications which regularly call `get_config`, expecting it to be async, will block their event loop while the request occurs. Calling `get_config` once on application startup is fine for async applications, as is done in the aiohttp extension, because the actual async part of the application isn't running yet. However, the fact that the application is async is irrelevant in that case.

**Comment by amenezes** [comment]
@joshuahaertel thanks for your question.

I'll try fix this in the next release.

**Comment by amenezes** [comment]
@joshuahaertel,

The project documentation was updated to exemplifying a little better the use of lib with asyncio.
- http://config-client.amenezes.net/docs/client/3.-asyncio/

Thank you for your comment and in case there is any doubt reopen this issue.
