### ISSUE TITLE
Supported python versions issue

### ISSUE THREAD

**Issue by denys-chura-perfectial** [amenezes/config-client#9]
Currently there are no _"python_requires"_ in setup.py so it is possible to install 
this package on un-supported python version _(for example on python 2.7 as I did)_.

Also I noticed that on PYPI page supported python versions starts from _"Python :: 3.5"_ but there are _f-strings_ used in code, which were added in python 3.6 ([PEP 498](https://www.python.org/dev/peps/pep-0498/)), so supported python version should start from python 3.6.

**Comment by amenezes** [comment]
@denys-chura-perfectial thanks for your contribution.

Issues fixed in the new version [0.2.1](https://github.com/amenezes/config-client/releases/tag/0.2.1).
